name: Create Production Builds

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  build_android:
    type: build # This job type creates a production build for Android
    params:
      platform: android
      profile: production
